import { create } from 'zustand';

export const useCommunicationBannerStore = create((set) => ({
  visible: false,
  title: '',
  body: '',
  deepLink: '/',
  priority: 'medium',
  imageUrl: null,
  kind: 'info',
  stage: null,
  ctaLabel: null,
  show: ({
    title,
    body,
    deepLink = '/',
    priority = 'medium',
    imageUrl = null,
    kind = 'info',
    stage = null,
    ctaLabel = null,
  }) => set({
    visible: true,
    title,
    body,
    deepLink,
    priority,
    imageUrl,
    kind,
    stage,
    ctaLabel,
  }),
  dismiss: () => set({
    visible: false,
    title: '',
    body: '',
    deepLink: '/',
    imageUrl: null,
    kind: 'info',
    stage: null,
    ctaLabel: null,
  }),
}));
