/** Categorías del Centro de Comunicación UrabApp */
export const COMM_CATEGORIES = {
  ORDERS: 'orders',
  MESSAGES: 'messages',
  PROMOTIONS: 'promotions',
  PAYMENTS: 'payments',
  SECURITY: 'security',
  SYSTEM: 'system',
  ACCOUNT: 'account',
  BUSINESS: 'business',
  MARKETPLACE: 'marketplace',
  SUPPORT: 'support',
  ADMIN: 'admin',
  ERRORS: 'errors',
  UPDATES: 'updates',
  REMINDERS: 'reminders',
  AI: 'ai',
  RECOMMENDATIONS: 'recommendations',
  MARKETING: 'marketing',
  URGENT: 'urgent',
};

export const COMM_CATEGORY_LABELS = {
  orders: 'Pedidos',
  messages: 'Mensajes',
  promotions: 'Promociones',
  payments: 'Pagos',
  security: 'Seguridad',
  system: 'Sistema',
  account: 'Cuenta',
  business: 'Comercios',
  marketplace: 'Marketplace',
  support: 'Soporte',
  admin: 'Administración',
  errors: 'Errores',
  updates: 'Actualizaciones',
  reminders: 'Recordatorios',
  ai: 'IA',
  recommendations: 'Recomendaciones',
  marketing: 'Marketing',
  urgent: 'Urgentes',
};

export const COMM_CATEGORY_ICONS = {
  orders: 'cart',
  messages: 'chat',
  promotions: 'promo',
  payments: 'money',
  security: 'shield',
  system: 'settings',
  account: 'profile',
  business: 'store',
  marketplace: 'search',
  support: 'headset',
  admin: 'admin',
  errors: 'alert',
  updates: 'refresh',
  reminders: 'bell',
  ai: 'sparkles',
  recommendations: 'star',
  marketing: 'megaphone',
  urgent: 'alert',
};
