import {
  Home,
  ClipboardList,
  ShoppingCart,
  ShoppingBag,
  User,
  Search,
  UtensilsCrossed,
  Bike,
  ShoppingBasket,
  Package,
  Wrench,
  Store,
  Sparkles,
  Star,
  Pill,
  Beer,
  Banana,
  Pizza,
  Utensils,
  Box,
  Tag,
  Soup,
  Shrimp,
  CupSoda,
  Sandwich,
  Egg,
  Droplets,
  Banknote,
  Landmark,
  Wallet,
  CreditCard,
  QrCode,
  Building2,
  MessageCircle,
  Headphones,
  Check,
  Link2,
  Lock,
  CheckSquare,
  Square,
  Medal,
  Dog,
  Hammer,
  Smartphone,
  Zap,
  Target,
  PartyPopper,
  Settings,
  Truck,
  MapPin,
  Bell,
  BarChart3,
  Users,
  TrendingUp,
  AlertCircle,
  WifiOff,
  Loader2,
  Moon,
  Sun,
  ChevronDown,
  Download,
  Share2,
  Plus,
} from 'lucide-react';
import { BRAND_ICON_KEYS } from './brand/UrabappBrandIcon';

/** Lucide por defecto — clave interna → componente */
export const LUCIDE_ICONS = {
  home: Home,
  orders: ClipboardList,
  pedidos: ShoppingBag,
  bag: ShoppingBag,
  cart: ShoppingCart,
  profile: User,
  search: Search,
  comida: UtensilsCrossed,
  mensajeria: Bike,
  tiendas: ShoppingBasket,
  envios: Package,
  reparaciones: Wrench,
  store: Store,
  package: Package,
  all: Sparkles,
  banana: Banana,
  fries: Pizza,
  pharmacy: Pill,
  market: ShoppingBasket,
  beer: Beer,
  plate: Utensils,
  bento: Box,
  star: Star,
  tag: Tag,
  soup: Soup,
  shrimp: Shrimp,
  juice: CupSoda,
  hotdog: Sandwich,
  soda: CupSoda,
  rice: Utensils,
  egg: Egg,
  lotion: Droplets,
  money: Banknote,
  bank: Landmark,
  wallet: Wallet,
  card: CreditCard,
  qr: QrCode,
  building: Building2,
  cash: Banknote,
  phone: Smartphone,
  chat: MessageCircle,
  headset: Headphones,
  delivery: Truck,
  link: Link2,
  check: Check,
  lock: Lock,
  checkboxOn: CheckSquare,
  checkboxOff: Square,
  medalGold: Medal,
  medalSilver: Medal,
  medalBronze: Medal,
  pet: Dog,
  tools: Hammer,
  mandado: Bike,
  empty: Package,
  food: Utensils,
  mobile: Smartphone,
  nequi: Smartphone,
  pse: Landmark,
  daviplata: Wallet,
  corresponsal: Store,
  bolt: Zap,
  target: Target,
  confetti: PartyPopper,
  settings: Settings,
  map: MapPin,
  bell: Bell,
  chart: BarChart3,
  users: Users,
  trend: TrendingUp,
  alert: AlertCircle,
  offline: WifiOff,
  loading: Loader2,
  moon: Moon,
  sun: Sun,
  chevronDown: ChevronDown,
  download: Download,
  share: Share2,
  add: Plus,
  plus: Plus,
};

/** Iconografía UI — Solar Bold Duotone: iconos completos, redondeados, estilo app premium */
function solar(name) {
  return `solar:${name}-bold-duotone`;
}

export const SOLAR_UI_ICONS = {
  home: solar('home-2'),
  orders: solar('clipboard-list'),
  cart: solar('cart-large-2'),
  profile: solar('user-circle'),
  search: solar('magnifer'),
  comida: solar('chef-hat'),
  food: solar('chef-hat'),
  plate: solar('cup-hot'),
  bento: solar('cup-hot'),
  soup: solar('cup-hot'),
  shrimp: solar('cup-hot'),
  juice: solar('cup-hot'),
  hotdog: solar('cup-hot'),
  soda: solar('cup-hot'),
  rice: solar('cup-hot'),
  egg: solar('cup-hot'),
  fries: solar('cup-hot'),
  banana: solar('cup-hot'),
  mensajeria: solar('scooter'),
  mandado: solar('scooter'),
  delivery: solar('delivery'),
  courier: solar('scooter'),
  envios: solar('box'),
  package: solar('plain-2'),
  tiendas: solar('shop-2'),
  shop: solar('shop'),
  store: solar('shop-2'),
  reparaciones: solar('station'),
  tools: solar('station'),
  ferreteria: solar('station'),
  all: solar('widget-5'),
  otros: solar('widget-5'),
  pharmacy: solar('pills'),
  market: solar('cart-large-minimalistic'),
  beer: solar('wineglass'),
  mobile: solar('smartphone-2'),
  phone: solar('smartphone-2'),
  moda: solar('t-shirt'),
  belleza: solar('perfume'),
  hogar: solar('home-smile-angle'),
  pet: solar('paw'),
  dog: solar('cat'),
  deportes: solar('dumbbells'),
  educacion: solar('square-academic-cap-2'),
  star: solar('star'),
  tag: solar('tag'),
  favorite: solar('heart'),
  money: solar('banknote-2'),
  cash: solar('banknote-2'),
  bank: solar('buildings-2'),
  wallet: solar('wallet-money'),
  card: solar('card'),
  qr: solar('qr-code'),
  building: solar('buildings-2'),
  chat: solar('chat-round-dots'),
  headset: solar('headphones-round'),
  map: solar('map-point'),
  location: solar('map-point'),
  lock: solar('lock-password'),
  link: solar('link'),
  check: solar('check-circle'),
  checkboxOn: solar('check-square'),
  checkboxOff: solar('record-circle'),
  medalGold: solar('medal-star'),
  medalSilver: solar('medal-star'),
  medalBronze: solar('medal-star'),
  bolt: solar('bolt'),
  target: solar('target'),
  confetti: solar('confetti'),
  settings: solar('settings'),
  bell: solar('bell'),
  chart: solar('chart-2'),
  users: solar('users-group-rounded'),
  trend: solar('graph-up'),
  alert: solar('danger-circle'),
  offline: solar('wi-fi-router-minimalistic'),
  loading: 'lucide:loader-2',
  moon: solar('moon'),
  sun: solar('sun-2'),
  chevronDown: solar('alt-arrow-down'),
  download: solar('download-minimalistic'),
  share: solar('share'),
  add: solar('add-circle'),
  filter: solar('filter'),
  edit: solar('pen-2'),
  delete: solar('trash-bin-trash'),
  back: solar('arrow-left'),
  close: solar('close-circle'),
  help: solar('question-circle'),
  more: solar('menu-dots'),
  scan: solar('scanner'),
  delivered: solar('check-circle'),
  processing: solar('hourglass'),
  pending: solar('clock-circle'),
  urgent: solar('danger-circle'),
  verified: solar('shield-check'),
  promo: solar('gift'),
  express: solar('rocket-2'),
  scheduled: solar('calendar'),
  empty: solar('mailbox'),
  nequi: solar('smartphone-2'),
  pse: solar('card'),
  daviplata: solar('wallet-money'),
  corresponsal: solar('shop-2'),
  lotion: solar('cosmetic'),
};

/** Iconify — UI Solar + marcas externas */
export const ICONIFY_ICONS = {
  ...SOLAR_UI_ICONS,
  nequi_brand: 'simple-icons:nequi',
  daviplata_brand: 'simple-icons:davivienda',
  pse_brand: 'mdi:bank-transfer',
  whatsapp: 'mdi:whatsapp',
  instagram: 'mdi:instagram',
};

export const EMOJI_TO_ICON = {
  '🏠': 'home',
  '📋': 'orders',
  '🛒': 'cart',
  '👤': 'profile',
  '🔍': 'search',
  '🍔': 'comida',
  '🛵': 'mensajeria',
  '📦': 'package',
  '🏪': 'store',
  '✨': 'all',
  '⭐': 'star',
  '💊': 'pharmacy',
  '🍺': 'beer',
  '🍌': 'banana',
  '🍟': 'fries',
  '🔧': 'reparaciones',
  '🐾': 'pet',
  '📱': 'mobile',
  '💬': 'chat',
  '🎧': 'headset',
  '✅': 'check',
  '📸': 'instagram',
  '🔗': 'link',
  '🍽️': 'plate',
  '🍱': 'bento',
  '🏷️': 'tag',
  '🍲': 'soup',
  '🍤': 'shrimp',
  '🥤': 'juice',
  '🌭': 'hotdog',
  '🍚': 'rice',
  '🥚': 'egg',
  '🧴': 'lotion',
  '💵': 'cash',
  '🏦': 'bank',
  '💜': 'wallet',
  '💳': 'card',
  '📲': 'qr',
  '🏛️': 'building',
  '🥇': 'medalGold',
  '🥈': 'medalSilver',
  '🥉': 'medalBronze',
  '🔒': 'lock',
  '⬜': 'checkboxOff',
};

export const CATEGORY_ICONS = {
  comida: 'comida',
  mensajeria: 'mensajeria',
  tiendas: 'store',
  envios: 'envios',
  reparaciones: 'tools',
  farmacia: 'pharmacy',
  mercado: 'market',
  licoreria: 'beer',
  mandados: 'mensajeria',
  mascotas: 'pet',
  tecnologia: 'mobile',
  moda: 'moda',
  belleza: 'belleza',
  hogar: 'hogar',
  deportes: 'deportes',
  educacion: 'educacion',
  ferreteria: 'ferreteria',
  otros: 'otros',
};

export const ICON_PICKER_OPTIONS = [
  'store', 'comida', 'pharmacy', 'market', 'beer', 'mensajeria', 'envios',
  'pet', 'mobile', 'moda', 'belleza', 'hogar', 'deportes', 'educacion',
  'ferreteria', 'tools', 'package', 'star', 'tag',
];

export function resolveIconKey(value) {
  if (!value) return 'store';
  if (EMOJI_TO_ICON[value]) return EMOJI_TO_ICON[value];
  if (ICONIFY_ICONS[value] || LUCIDE_ICONS[value] || BRAND_ICON_KEYS.has(value)) return value;
  return 'store';
}

export function iconForCategory(categoryId) {
  return CATEGORY_ICONS[categoryId] || 'store';
}
